### ISSUE TITLE
maxValue parameter should decrease the foor loop count instead of throwing error

### ISSUE THREAD

**Issue by gula123** [gherking/gherking#31]
**Steps**
1. Add 1 as maxValue for for loops
2. Use a greater number for a scenario loop count then the given maxValue e.g.: @loop(3)

**Actual results:**
It throws the following error on execution: "throw new Error(`Iterator ${iterator} exceeds maximum value of ${this.config.maIterator}.`)"

**Change request/Improvement idea**
maxValue should decrease higher loop counts to the value of the given maxValue

**Comment by szikszail** [comment]
Fixed in https://github.com/gherking/gpc-for-loop/pull/1/commits/2d1b9325eea693e8f4416b5fb5686a11fb4352c0
