### ISSUE TITLE
Feature files are not initialized and cleaned up upon initializaton of bin/precompile.js

### ISSUE THREAD

**Issue by garrymann** [gherking/gherking#33]
Target: Feature files should be deleted from the dist folder during the precompilizaton.

Problem: If we keep the previously generated Feature files as cache it could happen the content is not the one as we expect due to modifications since their creation.
For example:

Git branch A have a Z.feature. Compile phase completes. dist/Z.feature is created with content ASD. 
Modify the content to FGH.
eg add a tag like @current

switch to branch B and modify the content of Z.feature to XYZ. Run the precompiler. As a result the Z.feature will hold the FGH content instead of XYZ content. 
@current will remain

Suggested solution: Always remove the files as init and re-generate them with the precompiler.

**Comment by szikszail** [comment]
@garrymann the new `gherking@2.0.0` is released and this issue is fixed in it (all existing precompilers will be released in a couple of days as well).
