### ISSUE TITLE
Copy feature files to destination folder based on Cucumber tags

### ISSUE THREAD

**Issue by verebd** [gherking/gherking#39]
It would be good if the precompiler could copy feature files to the destination folder (or delete files from the destination folder) based on Cucumber tags.
The idea came up regarding parallel filtered testing in Protractor. When filtered tests are running parallel, the Protractor opens a WebDriver instance to each feature files, even when it does not contain any scenario which should run. It can extend the runtime in case of lots of feature files.
Could you please consider if this solution is possible?
Thank you in advance.

**Comment by szikszail** [comment]
This will be handled with #40
