### ISSUE TITLE
[IMPR] Load and manipulate "features" as strings rather than files

### ISSUE THREAD

**Issue by haikyuu** [gherking/gherking#80]
## Summary

Load and manipulate "features" as strings rather than files

e.g:
```
let ast = await compiler.load(`
  Feature: Addition
    Scenario: Adding two numbers works

	Given I have two numbers 12 and 4
	When I add them
	Then I should obtain 16
`)
```
## Use cases

I'm writing a cucumber plugin for vitest. And I already receive the source of the file. So I could skip a file system read like that.

## Example

```
export default function ccPlugin(){
  return { transform: (source, id)=> {
    let ast = await compiler.load(source); // rather than id
  }}
}
```

**Comment by szikszail** [comment]
Hi @haikyuu, it is a good idea! We will figure out how to include this feature in GherKing, and let you know.

**Comment by szikszail** [comment]
### Solution

- [ ] Implement `parse(content: string): Promise<Document>` function to [gherkin-io](https://github.com/gherking/gherkin-io).
- [ ] Re-export `parse` in gherking

**Comment by szikszail** [comment]
@haikyuu gherkin-io v1.2.0 is released. As gherking is mainly a CLI tool, we would not extend the API with the re-exporting of the parse function. Could you please check gherkin-io?

**Comment by haikyuu** [comment]
Thanks @szikszail I switched to using `gherkin-io` in my plugin instead. And it works like a charm 💯 

I was a bit confused and didn't know which library to use in which context.

I used `gherking` because I wanted to be able to use `process` eventually and I don't know if that's possible with `gherkin-io` 🤔

**Comment by szikszail** [comment]
In general, gherkin-io is for converting tonAST and back to file/string. If you want to process the AST, you need to use the process function from gherking.

In you case, when you receive the file content you can use gherkin-io/parse then gherking/process and finally depending if you want to write to a file or just convert to string, either gherkin-io or gherkin-formatter.

**Comment by haikyuu** [comment]
Sounds good, thank you.
